program: /contrastiveMRE/src/contrastive/main.py
data_dir:
save_dir: /contrastiveMRE/contrastive/output
save_model: 0
study: ATLAS+NITRC1+NITRC2+OA+MIMS+BMI+NOVA
model: resnet18
epochs: 50
batch_size: 32
lr: 1e-4
lr_decay: step
lr_decay_rate: 0.9
lr_decay_step: 10
optimizer: adam
momentum: 0.9
weight_decay: 5e-5
method: expw
kernel: rbf
sigma: 2
features_w_projection: 1
tf: noise
noise_std: 0.05
n_views: 2
modality: stiffness
norm_level: dataset_level
segmentation: None
brain_region: None
wandb_name: wandbname_placeholder
trial: 0
fold: 0
NN_nb_step_size: 0
end_NN_nb: 14
NN_nb_selection: 'manhattan'